version: '3.5'

services:

  rust-app:
    container_name: rust-app
    build:
      context: .
      dockerfile: env/Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - '8000:8000'
    environment:
      - USER=rust-app